//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int id { get; set; }
        public string comment1 { get; set; }
        public Nullable<int> post_id { get; set; }
        public string commet_by { get; set; }
    
        public virtual blog blog { get; set; }
        public virtual login login { get; set; }
    }
}
